library starwars.app_constants;

import 'dart:ui';

//Dashboard
const Color DASHBOARD_FIRSTCARD_FIRSTCOLOR = Color(0xfff4a340);
const Color DASHBOARD_FIRSTCARD_SECONDCOLOR = Color(0xffef6537);
const Color DASHBOARD_SECONDCARD_FIRSTCOLOR = Color(0xffec3d6d);
const Color DASHBOARD_SECONDCARD_SECONDCOLOR = Color(0xff9051e4);
const Color DASHBOARD_THIRTHCARD_FIRSTCOLOR = Color(0xff59C89E);
const Color DASHBOARD_THIRTHCARD_SECONDCOLOR = Color(0xff3066D6);
const Color DASHBOARD_FOURTHCARD_FIRSTCOLOR = Color(0xffF07562);
const Color DASHBOARD_FOURTHCARD_SECONDCOLOR = Color(0xffF4A03F);
const Color DASHBOARD_FIFTHCARD_FIRSTCOLOR = Color(0xffF3963E);
const Color DASHBOARD_FIFTHCARD_SECONDCOLOR = Color(0xffF9C647);
const Color DASHBOARD_SIXTHCARD_FIRSTCOLOR = Color(0xffEB51DA);
const Color DASHBOARD_SIXTHCARD_SECONDCOLOR = Color(0xff3D6BF5);

const Color PLANET_CARD_COLOR = Color(0xFF333366);

const Color CONNECTION_ERROR = Color(0xffFF0000);
const Color YELLOW_STARWARS = Color(0xfff6cc47);
